version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: helm
    directory: '/charts/chrisn-xyz/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/web/app/themes/chrisn-xyz/'
    schedule:
      interval: 'weekly'
    groups:
      regular-updates:
        update-types:
          - 'minor'
          - 'patch'
