apiVersion: v1
kind: Service
metadata:
  name: {{ include "chrisn-xyz.fullname" . }}
  labels:
    {{- include "chrisn-xyz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chrisn-xyz.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chrisn-xyz.fullname" . }}
  labels:
    {{- include "chrisn-xyz.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /chrisn-xyz
            pathType: Prefix
            backend:
              service:
                name: {{ include "chrisn-xyz.fullname" . }}
                port:
                  name: http
  tls:
    {{- with .Values.ingress.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
